name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build  --configuration Release --verbosity normal

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Denxorz.ObservableCollectionWithAddRange.nupkg
        path: ObservableCollectionWithAddRange/bin/**/*.nupkg
